name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        # MSRV and nightly
        version: [1.60.0, nightly]
    steps:
      - uses: actions/checkout@v3

      - name: Set toolchain
        run: |
          rustup set profile minimal
          rustup override set ${{ matrix.version }}

      - uses: Swatinem/rust-cache@v2.0.0

      - name: Rustfmt check
        if: matrix.version == '1.60.0'
        run: |
          rustup component add rustfmt
          cargo fmt --all -- --check

      - name: Run `cargo test` on workspace
        run: cargo test --workspace --exclude=phf_codegen_test

      - name: phf_macros UI test
        if: matrix.version == '1.60.0'
        working-directory: phf_macros_tests
        run: cargo test -- --ignored --test-threads=1

      - name: phf_codegen test
        run: cargo test -p phf_codegen_test

      - name: no_std build check
        working-directory: phf
        run: cargo build --no-default-features

      - name: unicase + macros features check
        run: cargo check -p unicase-example

      - name: check all features
        run: cargo check --all-features

      - name: check all targets
        if: matrix.version == 'nightly'
        run: cargo check --all-features --all-targets

      - name: update to minimal versions
        run: cargo +nightly update -Z minimal-versions

      - name: check all features with minimal versions
        run: cargo check --all-features

      - name: check all targets with minimal versions
        if: matrix.version == 'nightly'
        run: cargo check --all-features --all-targets
